---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment-ai-project-service.yaml
  - service-ai-project-service.yaml
images:
  - name: ai-project-service
    newName: ghcr.io/informasjonsforvaltning/ai-project-service
    newTag: $(GIT_COMMIT_SHA)
