---
apiVersion: v1
kind: Service
metadata:
  name: ai-project-service
spec:
  selector:
    app: ai-project-service
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
